[platformio]
data_dir = visualizer
default_envs = esp32_wifi_base_dashboard

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
    -DAPP_STANDALONE_BENCH=1
    -DAPP_WIFI_DASHBOARD=1
    -DAPP_BASE_BENCH=1
lib_deps =
    links2004/WebSockets @ ^2.4.1

[env:esp32_wifi_base_dashboard]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}
board_build.filesystem = spiffs
board_build.partitions = audix_wifi_spiffs.csv

[env:esp32dev]
extends = env:esp32_wifi_base_dashboard
